name: manufaktur
favicon: null
layout_spectrum: 0.6959991154726595
typography_spectrum: 0.6751021575182676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.14718685112893581
  lightness: 0.9543566005304456
  saturation: 0.8935128666926175
  rhythmicContrast: 0.22822471125982702
purpose: []
